// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalFinanceManager.Data;

#nullable disable

namespace PersonalFinanceManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260103230037_FixNullabilityIssues")]
    partial class FixNullabilityIssues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("PersonalFinanceManager.Data.Entities.Acordo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataAcordo")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PendenciaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("DataAcordo");

                    b.HasIndex("PendenciaId");

                    b.ToTable("Acordos", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceManager.Data.Entities.CartaoCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Banco")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DiaFechamento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Limite")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("Nome");

                    b.ToTable("CartoesCredito", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceManager.Data.Entities.NotificationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cancelada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("DataAgendamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataEnvio")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enviada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataAgendamento");

                    b.HasIndex("Enviada");

                    b.HasIndex("NotificationId")
                        .IsUnique();

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceManager.Data.Entities.Parcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AcordoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PendenciaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AcordoId");

                    b.HasIndex("DataVencimento");

                    b.HasIndex("Status");

                    b.HasIndex("PendenciaId", "NumeroParcela");

                    b.ToTable("Parcelas", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceManager.Data.Entities.Pendencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CartaoCreditoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Parcelada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Prioridade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoDivida")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CartaoCreditoId");

                    b.HasIndex("DataCriacao");

                    b.HasIndex("Status");

                    b.ToTable("Pendencias", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceManager.Data.Entities.Recebimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPrevista")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataRecebimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RecebimentoCompleto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("ValorEsperado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorRecebido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("DataPrevista");

                    b.HasIndex("RecebimentoCompleto");

                    b.ToTable("Recebimentos", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceManager.Data.Entities.Acordo", b =>
                {
                    b.HasOne("PersonalFinanceManager.Data.Entities.Pendencia", "Pendencia")
                        .WithMany("Acordos")
                        .HasForeignKey("PendenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pendencia");
                });

            modelBuilder.Entity("PersonalFinanceManager.Data.Entities.Parcela", b =>
                {
                    b.HasOne("PersonalFinanceManager.Data.Entities.Acordo", "Acordo")
                        .WithMany("Parcelas")
                        .HasForeignKey("AcordoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("PersonalFinanceManager.Data.Entities.Pendencia", "Pendencia")
                        .WithMany("Parcelas")
                        .HasForeignKey("PendenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acordo");

                    b.Navigation("Pendencia");
                });

            modelBuilder.Entity("PersonalFinanceManager.Data.Entities.Pendencia", b =>
                {
                    b.HasOne("PersonalFinanceManager.Data.Entities.CartaoCredito", "CartaoCredito")
                        .WithMany("Pendencias")
                        .HasForeignKey("CartaoCreditoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CartaoCredito");
                });

            modelBuilder.Entity("PersonalFinanceManager.Data.Entities.Acordo", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("PersonalFinanceManager.Data.Entities.CartaoCredito", b =>
                {
                    b.Navigation("Pendencias");
                });

            modelBuilder.Entity("PersonalFinanceManager.Data.Entities.Pendencia", b =>
                {
                    b.Navigation("Acordos");

                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
